### ISSUE TITLE
macOS Monterey - getDoNotDisturb is not working v 1.3.6

### ISSUE THREAD

**Issue by nbashkankov** [felixrieseberg/macos-notification-state#26]
Hello,

Looks like package not working with new macOS version - 
@felixrieseberg @MarshallOfSound - could you please help?

**Comment by Fiser12** [comment]
Checked on my app and it's working, thanks!. However I haven't checked it on Apple Silicon, I haven't one.

**Comment by nbashkankov** [comment]
@Fiser12 - Thank you

**Comment by nbashkankov** [comment]
@Fiser12 merged your changes to #27 🤝

**Comment by timothylui** [comment]
Any idea when this will get released?

**Comment by nbashkankov** [comment]
@felixrieseberg Hello - do you have concerns preventing to merge #27 ?

**Comment by nbashkankov** [comment]
fixed by #27 and published as 2.0.0 https://www.npmjs.com/package/macos-notification-state/v/2.0.0

**Comment by Fiser12** [comment]
Perfect! Thanks a lot for your help!
