### ISSUE TITLE
npm install failed on Windows 

### ISSUE THREAD

**Issue by nbashkankov** [felixrieseberg/macos-notification-state#28]
Hello, @felixrieseberg 

i use your package in Electron application which is also built for Windows platform so on npm install it fails.

node ensure-sdk.js which you added recently on preinstall fails on Windows 
https://github.com/felixrieseberg/macos-notification-state/commit/c61eb0ea3341d5b99cf4f4fa208ee10a87016db0

i see there is env.MACOS_NOTIFICATION_STATE_NO_SDK_CHECK to avoid - but it requires update for windows built environment - which is not comfortable as was before and requires additional effort

**Comment by nbashkankov** [comment]
added quick fix - please check

**Comment by felixrieseberg** [comment]
Man, I’m dumb. Thanks for catching it.

**Comment by nbashkankov** [comment]
fixed
