### ISSUE TITLE
MacOS 13 Ventura support

### ISSUE THREAD

**Issue by nbashkankov** [felixrieseberg/macos-notification-state#37]
Hello, @felixrieseberg 

I see commit from @MarshallOfSound - but looks like DND still not working on MacOS 13.
I run tests locally - 

```
 getDoNotDisturb / getNotificationState test, interactive
     Please enable do not disturb. Starting test in 0s...
2022-11-14 13:33:14.390 node[76078:868321] Failed to open ÒÏM‡, error Error Domain=NSCocoaErrorDomain Code=257 "The file “Assertions.json” couldn’t be opened because you don’t have permission to view it." UserInfo={NSFilePath=/Users/{user}/Library/DoNotDisturb/DB/Assertions.json, NSUnderlyingError=0x10ec04110 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
2022-11-14 13:33:14.390 node[76078:868321] Failed to open ÒÏM‡, error Error Domain=NSCocoaErrorDomain Code=257 "The file “ModeConfigurations.json” couldn’t be opened because you don’t have permission to view it." UserInfo={NSFilePath=/Users/{user}/Library/DoNotDisturb/DB/ModeConfigurations.json, NSUnderlyingError=0x10ec041d0 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
2022-11-14 13:33:14.390 node[76078:868321] Failed to open ÒÏM‡, error Error Domain=NSCocoaErrorDomain Code=257 "The file “Assertions.json” couldn’t be opened because you don’t have permission to view it." UserInfo={NSFilePath=/Users/{user}/Library/DoNotDisturb/DB/Assertions.json, NSUnderlyingError=0x10ec04200 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
```

As you can see - OS blocks access to JSON files with Focus mode information.

Also tried inside Electron app - no luck 2.0.2 - not working on MacOS 13 

```
Looks like problem with "Full disk Access" permission.
Which now blocks access to "~/Library/DoNotDisturb/.."
```

I have an idea - https://developer.apple.com/documentation/usernotifications/handling_communication_notifications_and_focus_status_updates?changes=_2 - here section "Request Focus Status"

**But the problem here is - 
/// Requests current focus status.
/// Requires UserNotifications and FocusStatus to be authorized and Communication Notifications capability enabled for the app's target.**

Here i made sample app with xcode which works on Ventura - 
To make it work inside Electron app - there should be entitlement added "**com.apple.developer.usernotifications.communication**" plus sign with provisioningProfile with Communication Notification.
@MarshallOfSound @felixrieseberg - any other ideas?

```
#import <Cocoa/Cocoa.h>
#import <Foundation/Foundation.h>
#import <Intents/Intents.h>
#import <NotificationCenter/NotificationCenter.h>
#import <UserNotifications/UserNotifications.h>

int main(int argc, const char * argv[]) {
    @autoreleasepool {
        // Setup code that might create autoreleased objects goes here.
        // https://developer.apple.com/documentation/usernotifications/handling_communication_notifications_and_focus_status_updates?changes=_2
        // UserNotifications authorized for parent app (target).
        UNAuthorizationOptions authOptions = UNAuthorizationOptionAlert |
                UNAuthorizationOptionSound | UNAuthorizationOptionBadge;

        [[UNUserNotificationCenter currentNotificationCenter] requestAuthorizationWithOptions:authOptions
                completionHandler:^(BOOL granted, NSError * _Nullable error) {
                     NSLog(@"notifications granted: %i %@",granted, error);
                }];
        
        
        // FocusStatusCenter authorized for parent app (target).
        INFocusStatusCenter *defaultCenterRef = [INFocusStatusCenter defaultCenter];
        [defaultCenterRef requestAuthorizationWithCompletionHandler:^(INFocusStatusAuthorizationStatus status) {
            NSLog(@"request status %ld", status);
            
            NSLog(@"isFocused %@", [[defaultCenterRef focusStatus] isFocused]);
        }];
        
        // TO WORK Communication Notifications capability (entitlement) added to the parent app (target).
    }
    return NSApplicationMain(argc, argv);
}
```

**Comment by nbashkankov** [comment]
Looks like problem only valid for sandboxed apps. ( with com.apple.security.app-sandbox in plist)

**Comment by nbashkankov** [comment]
@felixrieseberg  @MarshallOfSound  - please check #38

**Comment by soundar-m** [comment]
Hey @nbashkankov 
Thanks much for working on this.

Since the PR was merged, i tried installing and ran into this issue while compiling.
<img width="627" alt="image" src="https://github.com/felixrieseberg/macos-notification-state/assets/65405184/099b6763-46f2-44c6-93b6-c25469a2d9dc">

SDK version is 11.3 and i rebuild the module manually using node-gyp after installing.
Any idea why this occurs ? 
TIA 🙏

**Comment by nbashkankov** [comment]
@soundar-m INFocusStatusCenter available since MacOS SDK 12 
https://developer.apple.com/documentation/sirikit/infocusstatuscenter/
you can install sdk separatly and switch to it ( by xcode-select --switch)
or you can get newer XCode. (or it can be in separate app and also could be switched for build by xcode-select --switch)
it needed only for build time - in runtime there is bunch checks so it will work on various MacOS versions

Looks like i miss some guards in code changes to notify about min required MacOS SDK for build.
